# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'limbo-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - '172.31.6.111:8081'
          - '172.31.0.172:8081'
        labels:
          service: 'limbo-exchange-web-service'
      - targets:
          - '172.31.0.172:8081'
        labels:
          service: 'limbo-exchange-service'
      - targets:
          - '172.31.6.111:8081'
        labels:
          service: 'limbo-market-service'
      - targets:
          - '172.31.6.83:8081'
          - '172.31.7.248:8081'
          - '172.31.0.149:8081'
          - '172.31.7.109:8081'
        labels:
          service: 'limbo-api-gateway'
      - targets:
          - '172.31.6.83:8081'
          - '172.31.7.248:8081'
        labels:
          service: 'limbo-p2p-service'
      - targets:
          - '172.31.6.83:8081'
          - '172.31.7.248:8081'
          - '172.31.0.149:8081'
          - '172.31.7.109:8081'
        labels:
          service: 'limbo-user-service'
      - targets:
          - '172.31.0.149:8081'
          - '172.31.7.109:8081'
        labels:
          service: 'limbo-active-service'
      - targets:
          - '172.31.0.149:8081'
          - '172.31.7.109:8081'
        labels:
          service: 'limbo-agent-service'
      - targets:
          - '172.31.0.172:8081'
        labels:
          service: 'limbo-mmcorporate-service'
      - targets:
          - '172.31.6.111:8081'
        labels:
          service: 'limbo-future-admin-service'
      - targets:
          - '172.31.6.111:8081'
        labels:
          service: 'limbo-future-rebate-service'
      - targets:
          - '172.31.6.111:8081'
        labels:
          service: 'limbo-financial-service'
      - targets:
          - '172.31.6.111:8081'
        labels:
          service: 'limbo-option-service'
      - targets:
          - '172.31.6.111:8081'
          - '172.31.6.206:8081'
          - '172.31.0.218:8081'
        labels:
          service: 'limbo-robot-normal-service'
      - targets:
          - '172.31.3.161:8081'
        labels:
          service: 'limbo-admin-service'