# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'limbo-services'
    metrics_path: '/actuator/prometheus'
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):\d+'
        target_label: __tmp_ip
      - source_labels: [service, __tmp_ip]
        separator: ''
        regex: '(.*)(.*)'
        target_label: instance
        replacement: '${1}@${2}'
    static_configs:
      - targets:
          - '172.31.6.111:6092'
          - '172.31.0.172:6092'
        labels:
          service: 'limbo-exchange-web-service'
      - targets:
          - '172.31.0.172:6003'
        labels:
          service: 'limbo-exchange-service'
      - targets:
          - '172.31.6.111:6004'
        labels:
          service: 'limbo-market-service'
      - targets:
          - '172.31.6.83:9001'
          - '172.31.7.248:9001'
          - '172.31.0.149:9001'
          - '172.31.7.109:9001'
        labels:
          service: 'limbo-api-gateway'
      - targets:
          - '172.31.6.83:6006'
          - '172.31.7.248:6006'
        labels:
          service: 'limbo-p2p-service'
      - targets:
          - '172.31.6.83:6001'
          - '172.31.7.248:6001'
          - '172.31.0.149:6001'
          - '172.31.7.109:6001'
        labels:
          service: 'limbo-user-service'
      - targets:
          - '172.31.0.149:6002'
          - '172.31.7.109:6002'
        labels:
          service: 'limbo-active-service'
      - targets:
          - '172.31.0.149:5001'
          - '172.31.7.109:5001'
        labels:
          service: 'limbo-agent-service'
      - targets:
          - '172.31.0.172:6024'
        labels:
          service: 'limbo-mmcorporate-service'
      - targets:
          - '172.31.6.111:6089'
        labels:
          service: 'limbo-future-admin-service'
      - targets:
          - '172.31.6.111:6078'
        labels:
          service: 'limbo-future-rebate-service'
      - targets:
          - '172.31.6.111:6008'
        labels:
          service: 'limbo-financial-service'
      - targets:
          - '172.31.6.111:6012'
        labels:
          service: 'limbo-option-service'
      - targets:
          - '172.31.6.111:20000'
          - '172.31.6.206:20000'
          - '172.31.0.218:20000'
        labels:
          service: 'limbo-robot-normal-service'
      - targets:
          - '172.31.3.161:6010'
        labels:
          service: 'limbo-admin-service'